#!/usr/bin/env node
// Regenerates the shared "More open source from Brandon" footer from apps.json
// and writes it into every README listed in repos.json.
//
//   node tools/sync-footer.mjs              # write footer.md + every target README
//   node tools/sync-footer.mjs --check      # exit 1 if any target is out of date
//   node tools/sync-footer.mjs --print      # print the block, write nothing
//   node tools/sync-footer.mjs ../Plozz     # limit to one or more target paths
//
// A target README opts in by containing the marker pair below. If the markers
// are absent the block is appended once, so adding a new repo means listing it
// in repos.json and re-running this script.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const START = "<!-- app-family:start -->";
const END = "<!-- app-family:end -->";

const config = JSON.parse(readFileSync(join(ROOT, "apps.json"), "utf8"));
const { targets } = JSON.parse(readFileSync(join(ROOT, "repos.json"), "utf8"));

const url = (p) => `${config.cdn.replace(/\/$/, "")}/${p.replace(/^\//, "")}`;

// Deliberately table-free: GitHub styles <table> cells with borders and zebra
// striping, which reads as an opaque box behind every icon.
function render({ includeAuthor = true } = {}) {
  const size = config.logoSize;
  const gap = "&nbsp;".repeat(6);

  const row = config.apps
    .map(
      (app) =>
        `<a href="${app.repo}" title="${app.name} — ${app.tagline}"><img src="${url(app.logo)}" width="${size}" height="${size}" alt="${app.name}" /></a>`
    )
    .join(`\n  ${gap}\n  `);

  const names = config.apps
    .map((app) => `<a href="${app.repo}"><b>${app.name}</b></a>`)
    .join(" &nbsp;·&nbsp; ");

  const a = config.author;

  const author = includeAuthor
    ? `
<p align="center">
  <a href="${a.url}">
    <picture>
      <source media="(prefers-color-scheme: dark)" srcset="${url(a.logoDark)}" />
      <img src="${url(a.logoLight)}" height="${a.height}" alt="${a.name}" />
    </picture>
  </a>
</p>
`
    : "";

  return `${START}
<!-- Generated by https://github.com/thatcube/brando — edit apps.json there, not this block. -->

---

<p align="center"><b>${config.heading}</b></p>

<p align="center">
  ${row}
</p>

<p align="center">
  ${names}
</p>
${author}${END}`;
}

function apply(readme, block) {
  const current = readFileSync(readme, "utf8");
  const hasMarkers = current.includes(START) && current.includes(END);
  let next;
  if (hasMarkers) {
    const pattern = new RegExp(
      `${START.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}[\\s\\S]*?${END.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}`
    );
    next = current.replace(pattern, block);
  } else {
    next = `${current.replace(/\s*$/, "")}\n\n${block}\n`;
  }
  return { current, next, changed: current !== next, appended: !hasMarkers };
}

const args = process.argv.slice(2);
const check = args.includes("--check");
const printOnly = args.includes("--print");
const only = args.filter((a) => !a.startsWith("--"));

const block = render();

if (printOnly) {
  console.log(block);
  process.exit(0);
}

writeFileSync(join(ROOT, "footer.md"), `${block}\n`);

// A path passed on the command line that isn't in repos.json is still valid —
// Plozz and friends are often worked on in a git worktree, which lives nowhere
// near the checkout listed here.
const known = new Set(targets.map((t) => resolve(ROOT, t.path)));
const adhoc = only
  .filter((o) => !known.has(resolve(o)))
  .map((o) => ({ name: `${o} (ad-hoc)`, path: resolve(o) }));

const queue = only.length
  ? [...targets.filter((t) => only.some((o) => resolve(o) === resolve(ROOT, t.path))), ...adhoc]
  : targets;

let stale = 0;
for (const target of queue) {
  const readme = resolve(ROOT, target.path, target.readme ?? "README.md");
  if (!existsSync(readme)) {
    console.warn(`skip   ${target.name} — no README at ${readme}`);
    continue;
  }
  const targetBlock = target.omitAuthorLogo ? render({ includeAuthor: false }) : block;
  const { next, changed, appended } = apply(readme, targetBlock);
  if (!changed) {
    console.log(`ok     ${target.name}`);
    continue;
  }
  stale += 1;
  if (check) {
    console.error(`stale  ${target.name}`);
    continue;
  }
  writeFileSync(readme, next);
  console.log(`${appended ? "added " : "update"} ${target.name}`);
}

if (check && stale) {
  console.error(`\n${stale} README(s) out of date — run: node tools/sync-footer.mjs`);
  process.exit(1);
}
